### ISSUE TITLE
Cannot execute bash on Windows OS

### ISSUE THREAD

**Issue by tainguyenphat74** [phuctm97/dbsky#1]
Hi @phuctm97 

Currently, Windows does not support running the bash script via a command in `package.json`, such as `./prepare.sh` and `./check.sh`. It works perfectly on Linux/macOS.
![image](https://github.com/user-attachments/assets/88e2edfa-6128-4850-8384-21b2f508f5fc)

I have investigated and tried to use another way by using `bash`, and it works well. `bash` is default for Linux/macOS (Homebrew), and Windows (Git bash).

I hope it makes sense for you. If everything is clear, I will make a PR for this matter.

Thanks.

**Comment by phuctm97** [comment]
The script is using bash right?

**Comment by tainguyenphat74** [comment]
Yes. Just change the executing way  that can run on Windows and Linux/macOS as well.

**Comment by tainguyenphat74** [comment]
Hello @phuctm97 

I cannot execute `npm install` even running on Git Bash:
![image](https://github.com/user-attachments/assets/fdbb2111-a83c-42b1-942a-c726a85047de)

I attempted to change to `bash prepare.sh` and `bash check.sh` which worked well on Windows. However, I spent a lot of time trying to discover why I could not execute `./prepare.sh` like Linux/macOS even executing on Git Bash (which supports running bash script). Because npm internally uses cmd.exe for running scripts, even if npm command itself is typed in Git Bash.

I updated npm script-shell to bash.exe and solved my problem. I can close this issue, but I think we should update README for more detail for Windows-ers. What do you think?

**Comment by phuctm97** [comment]
Interesting! Thank you for the explanation. I think we can use this issue to reference for other Windows devs in the future.

**Comment by tainguyenphat74** [comment]
Thanks for your support.
For anybody if you want to solve the problem, just override npm running bash scripts on Windows by the following command: `npm config set script-shell "C:\\Program Files\\Git\\bin\\bash.exe"`
